#pragma once

namespace ALMANAC
  {
  enum MONTHS{JANUARY = 1, FEBRUARY, MARCH, APRIL, MAY, JUNE, JULY, AUGUST, SEPTEMBER, OCTOBER, NOVEMBER, DECEMBER};
  enum SOILTYPE {stCLAY = 1, stSANDYCLAY, stSILTYCLAY, stCLAYLOAM, stSILTYCLAYLOAM, stSANDYCLAYLOAM, stLOAM, stSILTLOAM, stSANDYLOAM, stLOAMYSAND, stSAND, stSILT};
  enum SOILTYPEGROUP {stgCLAYGROUP = 1, stgSANDGROUP, stgLOAMGROUP, stgSILTGROUP};
  }