#pragma once

namespace ALMANAC
  {
    enum SOILTYPE {stCLAY = 1, stSANDYCLAY, stSILTYCLAY, stCLAYLOAM, stSILTYCLAYLOAM, stSANDYCLAYLOAM, stLOAM, stSILTLOAM, stSANDYLOAM, stLOAMYSAND, stSAND, stSILT};
  enum SOILTYPEGROUP {stgCLAYGROUP = 1, stgSANDGROUP, stgLOAMGROUP, stgSILTGROUP};


  }